/**
 * @fileoverview gRPC-Web generated client stub for wallet
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: shifter.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.wallet = require('./shifter_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wallet.ShifterServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.wallet.ShifterServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.wallet.GetFrontlinerBulkRequest,
 *   !proto.wallet.GetFrontlinerBulkResponse>}
 */
const methodDescriptor_ShifterService_GetFrontlinerBulk = new grpc.web.MethodDescriptor(
  '/wallet.ShifterService/GetFrontlinerBulk',
  grpc.web.MethodType.UNARY,
  proto.wallet.GetFrontlinerBulkRequest,
  proto.wallet.GetFrontlinerBulkResponse,
  /**
   * @param {!proto.wallet.GetFrontlinerBulkRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.wallet.GetFrontlinerBulkResponse.deserializeBinary
);


/**
 * @param {!proto.wallet.GetFrontlinerBulkRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.wallet.GetFrontlinerBulkResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.wallet.GetFrontlinerBulkResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.wallet.ShifterServiceClient.prototype.getFrontlinerBulk =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/wallet.ShifterService/GetFrontlinerBulk',
      request,
      metadata || {},
      methodDescriptor_ShifterService_GetFrontlinerBulk,
      callback);
};


/**
 * @param {!proto.wallet.GetFrontlinerBulkRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.wallet.GetFrontlinerBulkResponse>}
 *     Promise that resolves to the response
 */
proto.wallet.ShifterServicePromiseClient.prototype.getFrontlinerBulk =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/wallet.ShifterService/GetFrontlinerBulk',
      request,
      metadata || {},
      methodDescriptor_ShifterService_GetFrontlinerBulk);
};


module.exports = proto.wallet;

