// source: transaction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.transaction.GetTransactionsRequest', null, global);
goog.exportSymbol('proto.transaction.GetTransactionsResponse', null, global);
goog.exportSymbol('proto.transaction.TopUp', null, global);
goog.exportSymbol('proto.transaction.TopUpWalletRequest', null, global);
goog.exportSymbol('proto.transaction.Transaction', null, global);
goog.exportSymbol('proto.transaction.TransactionQueryCriteria', null, global);
goog.exportSymbol('proto.transaction.TransactionRPCResponse', null, global);
goog.exportSymbol('proto.transaction.Transfer', null, global);
goog.exportSymbol('proto.transaction.TransferMoneyRequest', null, global);
goog.exportSymbol('proto.transaction.Withdraw', null, global);
goog.exportSymbol('proto.transaction.WithdrawMoneyRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.TransactionRPCResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.TransactionRPCResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.TransactionRPCResponse.displayName = 'proto.transaction.TransactionRPCResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.TransactionQueryCriteria = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.TransactionQueryCriteria, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.TransactionQueryCriteria.displayName = 'proto.transaction.TransactionQueryCriteria';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.TransferMoneyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.TransferMoneyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.TransferMoneyRequest.displayName = 'proto.transaction.TransferMoneyRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.TopUpWalletRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.TopUpWalletRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.TopUpWalletRequest.displayName = 'proto.transaction.TopUpWalletRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.Transfer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.Transfer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.Transfer.displayName = 'proto.transaction.Transfer';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.TopUp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.TopUp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.TopUp.displayName = 'proto.transaction.TopUp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.Withdraw = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.Withdraw, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.Withdraw.displayName = 'proto.transaction.Withdraw';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.Transaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.Transaction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.Transaction.displayName = 'proto.transaction.Transaction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.GetTransactionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.GetTransactionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.GetTransactionsRequest.displayName = 'proto.transaction.GetTransactionsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.GetTransactionsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.transaction.GetTransactionsResponse.repeatedFields_, null);
};
goog.inherits(proto.transaction.GetTransactionsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.GetTransactionsResponse.displayName = 'proto.transaction.GetTransactionsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.WithdrawMoneyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.transaction.WithdrawMoneyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.transaction.WithdrawMoneyRequest.displayName = 'proto.transaction.WithdrawMoneyRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.TransactionRPCResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.TransactionRPCResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.TransactionRPCResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TransactionRPCResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    response: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.TransactionRPCResponse}
 */
proto.transaction.TransactionRPCResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.TransactionRPCResponse;
  return proto.transaction.TransactionRPCResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.TransactionRPCResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.TransactionRPCResponse}
 */
proto.transaction.TransactionRPCResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setResponse(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.TransactionRPCResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.TransactionRPCResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.TransactionRPCResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TransactionRPCResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponse();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 response = 1;
 * @return {number}
 */
proto.transaction.TransactionRPCResponse.prototype.getResponse = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TransactionRPCResponse} returns this
 */
proto.transaction.TransactionRPCResponse.prototype.setResponse = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.transaction.TransactionRPCResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TransactionRPCResponse} returns this
 */
proto.transaction.TransactionRPCResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.TransactionQueryCriteria.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.TransactionQueryCriteria.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.TransactionQueryCriteria} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TransactionQueryCriteria.toObject = function(includeInstance, msg) {
  var f, obj = {
    ownerid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    ownersourcetable: jspb.Message.getFieldWithDefault(msg, 2, ""),
    transactionuuid: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.TransactionQueryCriteria}
 */
proto.transaction.TransactionQueryCriteria.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.TransactionQueryCriteria;
  return proto.transaction.TransactionQueryCriteria.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.TransactionQueryCriteria} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.TransactionQueryCriteria}
 */
proto.transaction.TransactionQueryCriteria.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOwnerid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnersourcetable(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionuuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.TransactionQueryCriteria.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.TransactionQueryCriteria.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.TransactionQueryCriteria} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TransactionQueryCriteria.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOwnerid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getOwnersourcetable();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTransactionuuid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int64 OwnerID = 1;
 * @return {number}
 */
proto.transaction.TransactionQueryCriteria.prototype.getOwnerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TransactionQueryCriteria} returns this
 */
proto.transaction.TransactionQueryCriteria.prototype.setOwnerid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string OwnerSourceTable = 2;
 * @return {string}
 */
proto.transaction.TransactionQueryCriteria.prototype.getOwnersourcetable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TransactionQueryCriteria} returns this
 */
proto.transaction.TransactionQueryCriteria.prototype.setOwnersourcetable = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string TransactionUUID = 3;
 * @return {string}
 */
proto.transaction.TransactionQueryCriteria.prototype.getTransactionuuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TransactionQueryCriteria} returns this
 */
proto.transaction.TransactionQueryCriteria.prototype.setTransactionuuid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.TransferMoneyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.TransferMoneyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.TransferMoneyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TransferMoneyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    apikey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    sourceownerid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    sourceownertable: jspb.Message.getFieldWithDefault(msg, 3, ""),
    destinationownerid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    destinationownertable: jspb.Message.getFieldWithDefault(msg, 5, ""),
    idwalletupdateaction: jspb.Message.getFieldWithDefault(msg, 6, 0),
    ammount: jspb.Message.getFieldWithDefault(msg, 7, 0),
    description: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.TransferMoneyRequest}
 */
proto.transaction.TransferMoneyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.TransferMoneyRequest;
  return proto.transaction.TransferMoneyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.TransferMoneyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.TransferMoneyRequest}
 */
proto.transaction.TransferMoneyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setApikey(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSourceownerid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceownertable(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDestinationownerid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestinationownertable(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setIdwalletupdateaction(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAmmount(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.TransferMoneyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.TransferMoneyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.TransferMoneyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TransferMoneyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApikey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSourceownerid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getSourceownertable();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDestinationownerid();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getDestinationownertable();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIdwalletupdateaction();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getAmmount();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string apiKey = 1;
 * @return {string}
 */
proto.transaction.TransferMoneyRequest.prototype.getApikey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TransferMoneyRequest} returns this
 */
proto.transaction.TransferMoneyRequest.prototype.setApikey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 SourceOwnerID = 2;
 * @return {number}
 */
proto.transaction.TransferMoneyRequest.prototype.getSourceownerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TransferMoneyRequest} returns this
 */
proto.transaction.TransferMoneyRequest.prototype.setSourceownerid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string SourceOwnerTable = 3;
 * @return {string}
 */
proto.transaction.TransferMoneyRequest.prototype.getSourceownertable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TransferMoneyRequest} returns this
 */
proto.transaction.TransferMoneyRequest.prototype.setSourceownertable = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint64 DestinationOwnerID = 4;
 * @return {number}
 */
proto.transaction.TransferMoneyRequest.prototype.getDestinationownerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TransferMoneyRequest} returns this
 */
proto.transaction.TransferMoneyRequest.prototype.setDestinationownerid = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string DestinationOwnerTable = 5;
 * @return {string}
 */
proto.transaction.TransferMoneyRequest.prototype.getDestinationownertable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TransferMoneyRequest} returns this
 */
proto.transaction.TransferMoneyRequest.prototype.setDestinationownertable = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint64 IDWalletUpdateAction = 6;
 * @return {number}
 */
proto.transaction.TransferMoneyRequest.prototype.getIdwalletupdateaction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TransferMoneyRequest} returns this
 */
proto.transaction.TransferMoneyRequest.prototype.setIdwalletupdateaction = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 Ammount = 7;
 * @return {number}
 */
proto.transaction.TransferMoneyRequest.prototype.getAmmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TransferMoneyRequest} returns this
 */
proto.transaction.TransferMoneyRequest.prototype.setAmmount = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string Description = 8;
 * @return {string}
 */
proto.transaction.TransferMoneyRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TransferMoneyRequest} returns this
 */
proto.transaction.TransferMoneyRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.TopUpWalletRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.TopUpWalletRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.TopUpWalletRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TopUpWalletRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    apikey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ownerid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ownertable: jspb.Message.getFieldWithDefault(msg, 3, ""),
    idwalletupdateaction: jspb.Message.getFieldWithDefault(msg, 4, 0),
    ammount: jspb.Message.getFieldWithDefault(msg, 5, 0),
    description: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.TopUpWalletRequest}
 */
proto.transaction.TopUpWalletRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.TopUpWalletRequest;
  return proto.transaction.TopUpWalletRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.TopUpWalletRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.TopUpWalletRequest}
 */
proto.transaction.TopUpWalletRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setApikey(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setOwnerid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnertable(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setIdwalletupdateaction(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAmmount(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.TopUpWalletRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.TopUpWalletRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.TopUpWalletRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TopUpWalletRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApikey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOwnerid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getOwnertable();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIdwalletupdateaction();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getAmmount();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string apiKey = 1;
 * @return {string}
 */
proto.transaction.TopUpWalletRequest.prototype.getApikey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TopUpWalletRequest} returns this
 */
proto.transaction.TopUpWalletRequest.prototype.setApikey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 OwnerID = 2;
 * @return {number}
 */
proto.transaction.TopUpWalletRequest.prototype.getOwnerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TopUpWalletRequest} returns this
 */
proto.transaction.TopUpWalletRequest.prototype.setOwnerid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string OwnerTable = 3;
 * @return {string}
 */
proto.transaction.TopUpWalletRequest.prototype.getOwnertable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TopUpWalletRequest} returns this
 */
proto.transaction.TopUpWalletRequest.prototype.setOwnertable = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint64 IDWalletUpdateAction = 4;
 * @return {number}
 */
proto.transaction.TopUpWalletRequest.prototype.getIdwalletupdateaction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TopUpWalletRequest} returns this
 */
proto.transaction.TopUpWalletRequest.prototype.setIdwalletupdateaction = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 Ammount = 5;
 * @return {number}
 */
proto.transaction.TopUpWalletRequest.prototype.getAmmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TopUpWalletRequest} returns this
 */
proto.transaction.TopUpWalletRequest.prototype.setAmmount = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string Description = 6;
 * @return {string}
 */
proto.transaction.TopUpWalletRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TopUpWalletRequest} returns this
 */
proto.transaction.TopUpWalletRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.Transfer.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.Transfer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.Transfer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.Transfer.toObject = function(includeInstance, msg) {
  var f, obj = {
    sourcewalletid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sourceownerid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    sourceownertable: jspb.Message.getFieldWithDefault(msg, 3, ""),
    destwalletid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    destownerid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    destownertable: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.Transfer}
 */
proto.transaction.Transfer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.Transfer;
  return proto.transaction.Transfer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.Transfer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.Transfer}
 */
proto.transaction.Transfer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setSourcewalletid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setSourceownerid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceownertable(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setDestwalletid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setDestownerid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestownertable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.Transfer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.Transfer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.Transfer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.Transfer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSourcewalletid();
  if (f !== 0) {
    writer.writeSint64(
      1,
      f
    );
  }
  f = message.getSourceownerid();
  if (f !== 0) {
    writer.writeSint64(
      2,
      f
    );
  }
  f = message.getSourceownertable();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDestwalletid();
  if (f !== 0) {
    writer.writeSint64(
      4,
      f
    );
  }
  f = message.getDestownerid();
  if (f !== 0) {
    writer.writeSint64(
      5,
      f
    );
  }
  f = message.getDestownertable();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional sint64 SourceWalletID = 1;
 * @return {number}
 */
proto.transaction.Transfer.prototype.getSourcewalletid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Transfer} returns this
 */
proto.transaction.Transfer.prototype.setSourcewalletid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional sint64 SourceOwnerID = 2;
 * @return {number}
 */
proto.transaction.Transfer.prototype.getSourceownerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Transfer} returns this
 */
proto.transaction.Transfer.prototype.setSourceownerid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string SourceOwnerTable = 3;
 * @return {string}
 */
proto.transaction.Transfer.prototype.getSourceownertable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.Transfer} returns this
 */
proto.transaction.Transfer.prototype.setSourceownertable = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional sint64 DestWalletID = 4;
 * @return {number}
 */
proto.transaction.Transfer.prototype.getDestwalletid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Transfer} returns this
 */
proto.transaction.Transfer.prototype.setDestwalletid = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional sint64 DestOwnerID = 5;
 * @return {number}
 */
proto.transaction.Transfer.prototype.getDestownerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Transfer} returns this
 */
proto.transaction.Transfer.prototype.setDestownerid = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string DestOwnerTable = 6;
 * @return {string}
 */
proto.transaction.Transfer.prototype.getDestownertable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.Transfer} returns this
 */
proto.transaction.Transfer.prototype.setDestownertable = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.TopUp.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.TopUp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.TopUp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TopUp.toObject = function(includeInstance, msg) {
  var f, obj = {
    walletid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    ownerid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ownertable: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.TopUp}
 */
proto.transaction.TopUp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.TopUp;
  return proto.transaction.TopUp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.TopUp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.TopUp}
 */
proto.transaction.TopUp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setWalletid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setOwnerid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnertable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.TopUp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.TopUp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.TopUp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TopUp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWalletid();
  if (f !== 0) {
    writer.writeSint64(
      1,
      f
    );
  }
  f = message.getOwnerid();
  if (f !== 0) {
    writer.writeSint64(
      2,
      f
    );
  }
  f = message.getOwnertable();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional sint64 WalletID = 1;
 * @return {number}
 */
proto.transaction.TopUp.prototype.getWalletid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TopUp} returns this
 */
proto.transaction.TopUp.prototype.setWalletid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional sint64 OwnerID = 2;
 * @return {number}
 */
proto.transaction.TopUp.prototype.getOwnerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.TopUp} returns this
 */
proto.transaction.TopUp.prototype.setOwnerid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string OwnerTable = 3;
 * @return {string}
 */
proto.transaction.TopUp.prototype.getOwnertable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.TopUp} returns this
 */
proto.transaction.TopUp.prototype.setOwnertable = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.Withdraw.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.Withdraw.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.Withdraw} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.Withdraw.toObject = function(includeInstance, msg) {
  var f, obj = {
    walletid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    ownerid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ownertable: jspb.Message.getFieldWithDefault(msg, 3, ""),
    externalwalletid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    externalbankcode: jspb.Message.getFieldWithDefault(msg, 5, 0),
    externalacountnumber: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.Withdraw}
 */
proto.transaction.Withdraw.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.Withdraw;
  return proto.transaction.Withdraw.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.Withdraw} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.Withdraw}
 */
proto.transaction.Withdraw.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setWalletid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setOwnerid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnertable(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setExternalwalletid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setExternalbankcode(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setExternalacountnumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.Withdraw.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.Withdraw.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.Withdraw} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.Withdraw.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWalletid();
  if (f !== 0) {
    writer.writeSint64(
      1,
      f
    );
  }
  f = message.getOwnerid();
  if (f !== 0) {
    writer.writeSint64(
      2,
      f
    );
  }
  f = message.getOwnertable();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getExternalwalletid();
  if (f !== 0) {
    writer.writeSint64(
      4,
      f
    );
  }
  f = message.getExternalbankcode();
  if (f !== 0) {
    writer.writeSint64(
      5,
      f
    );
  }
  f = message.getExternalacountnumber();
  if (f !== 0) {
    writer.writeSint64(
      6,
      f
    );
  }
};


/**
 * optional sint64 WalletID = 1;
 * @return {number}
 */
proto.transaction.Withdraw.prototype.getWalletid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Withdraw} returns this
 */
proto.transaction.Withdraw.prototype.setWalletid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional sint64 OwnerID = 2;
 * @return {number}
 */
proto.transaction.Withdraw.prototype.getOwnerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Withdraw} returns this
 */
proto.transaction.Withdraw.prototype.setOwnerid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string OwnerTable = 3;
 * @return {string}
 */
proto.transaction.Withdraw.prototype.getOwnertable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.Withdraw} returns this
 */
proto.transaction.Withdraw.prototype.setOwnertable = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional sint64 ExternalWalletID = 4;
 * @return {number}
 */
proto.transaction.Withdraw.prototype.getExternalwalletid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Withdraw} returns this
 */
proto.transaction.Withdraw.prototype.setExternalwalletid = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional sint64 ExternalBankCode = 5;
 * @return {number}
 */
proto.transaction.Withdraw.prototype.getExternalbankcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Withdraw} returns this
 */
proto.transaction.Withdraw.prototype.setExternalbankcode = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional sint64 ExternalAcountNumber = 6;
 * @return {number}
 */
proto.transaction.Withdraw.prototype.getExternalacountnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Withdraw} returns this
 */
proto.transaction.Withdraw.prototype.setExternalacountnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.Transaction.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.Transaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.Transaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.Transaction.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionuuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    transferdetails: (f = msg.getTransferdetails()) && proto.transaction.Transfer.toObject(includeInstance, f),
    topupdetails: (f = msg.getTopupdetails()) && proto.transaction.TopUp.toObject(includeInstance, f),
    withdrawdetails: (f = msg.getWithdrawdetails()) && proto.transaction.Withdraw.toObject(includeInstance, f),
    idwalletupdateaction: jspb.Message.getFieldWithDefault(msg, 5, 0),
    walletupdateaction: jspb.Message.getFieldWithDefault(msg, 6, ""),
    idwalletlogstatus: jspb.Message.getFieldWithDefault(msg, 7, 0),
    walletlogstatus: jspb.Message.getFieldWithDefault(msg, 8, ""),
    ammount: jspb.Message.getFieldWithDefault(msg, 9, 0),
    description: jspb.Message.getFieldWithDefault(msg, 10, ""),
    createdat: jspb.Message.getFieldWithDefault(msg, 11, ""),
    colorcode: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.Transaction}
 */
proto.transaction.Transaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.Transaction;
  return proto.transaction.Transaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.Transaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.Transaction}
 */
proto.transaction.Transaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionuuid(value);
      break;
    case 2:
      var value = new proto.transaction.Transfer;
      reader.readMessage(value,proto.transaction.Transfer.deserializeBinaryFromReader);
      msg.setTransferdetails(value);
      break;
    case 3:
      var value = new proto.transaction.TopUp;
      reader.readMessage(value,proto.transaction.TopUp.deserializeBinaryFromReader);
      msg.setTopupdetails(value);
      break;
    case 4:
      var value = new proto.transaction.Withdraw;
      reader.readMessage(value,proto.transaction.Withdraw.deserializeBinaryFromReader);
      msg.setWithdrawdetails(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setIdwalletupdateaction(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setWalletupdateaction(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setIdwalletlogstatus(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setWalletlogstatus(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setAmmount(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedat(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setColorcode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.Transaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.Transaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.Transaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.Transaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionuuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTransferdetails();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.transaction.Transfer.serializeBinaryToWriter
    );
  }
  f = message.getTopupdetails();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.transaction.TopUp.serializeBinaryToWriter
    );
  }
  f = message.getWithdrawdetails();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.transaction.Withdraw.serializeBinaryToWriter
    );
  }
  f = message.getIdwalletupdateaction();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getWalletupdateaction();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getIdwalletlogstatus();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getWalletlogstatus();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getAmmount();
  if (f !== 0) {
    writer.writeSint64(
      9,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getCreatedat();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getColorcode();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional string TransactionUUID = 1;
 * @return {string}
 */
proto.transaction.Transaction.prototype.getTransactionuuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.setTransactionuuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Transfer TransferDetails = 2;
 * @return {?proto.transaction.Transfer}
 */
proto.transaction.Transaction.prototype.getTransferdetails = function() {
  return /** @type{?proto.transaction.Transfer} */ (
    jspb.Message.getWrapperField(this, proto.transaction.Transfer, 2));
};


/**
 * @param {?proto.transaction.Transfer|undefined} value
 * @return {!proto.transaction.Transaction} returns this
*/
proto.transaction.Transaction.prototype.setTransferdetails = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.clearTransferdetails = function() {
  return this.setTransferdetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.transaction.Transaction.prototype.hasTransferdetails = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional TopUp TopUpDetails = 3;
 * @return {?proto.transaction.TopUp}
 */
proto.transaction.Transaction.prototype.getTopupdetails = function() {
  return /** @type{?proto.transaction.TopUp} */ (
    jspb.Message.getWrapperField(this, proto.transaction.TopUp, 3));
};


/**
 * @param {?proto.transaction.TopUp|undefined} value
 * @return {!proto.transaction.Transaction} returns this
*/
proto.transaction.Transaction.prototype.setTopupdetails = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.clearTopupdetails = function() {
  return this.setTopupdetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.transaction.Transaction.prototype.hasTopupdetails = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Withdraw WithdrawDetails = 4;
 * @return {?proto.transaction.Withdraw}
 */
proto.transaction.Transaction.prototype.getWithdrawdetails = function() {
  return /** @type{?proto.transaction.Withdraw} */ (
    jspb.Message.getWrapperField(this, proto.transaction.Withdraw, 4));
};


/**
 * @param {?proto.transaction.Withdraw|undefined} value
 * @return {!proto.transaction.Transaction} returns this
*/
proto.transaction.Transaction.prototype.setWithdrawdetails = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.clearWithdrawdetails = function() {
  return this.setWithdrawdetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.transaction.Transaction.prototype.hasWithdrawdetails = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional uint64 IDWalletUpdateAction = 5;
 * @return {number}
 */
proto.transaction.Transaction.prototype.getIdwalletupdateaction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.setIdwalletupdateaction = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string WalletUpdateAction = 6;
 * @return {string}
 */
proto.transaction.Transaction.prototype.getWalletupdateaction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.setWalletupdateaction = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional uint64 IDWalletLogStatus = 7;
 * @return {number}
 */
proto.transaction.Transaction.prototype.getIdwalletlogstatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.setIdwalletlogstatus = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string WalletLogStatus = 8;
 * @return {string}
 */
proto.transaction.Transaction.prototype.getWalletlogstatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.setWalletlogstatus = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional sint64 Ammount = 9;
 * @return {number}
 */
proto.transaction.Transaction.prototype.getAmmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.setAmmount = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string Description = 10;
 * @return {string}
 */
proto.transaction.Transaction.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string CreatedAt = 11;
 * @return {string}
 */
proto.transaction.Transaction.prototype.getCreatedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string ColorCode = 12;
 * @return {string}
 */
proto.transaction.Transaction.prototype.getColorcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.Transaction} returns this
 */
proto.transaction.Transaction.prototype.setColorcode = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.GetTransactionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.GetTransactionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.GetTransactionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.GetTransactionsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    apikey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    querycriteria: (f = msg.getQuerycriteria()) && proto.transaction.TransactionQueryCriteria.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.GetTransactionsRequest}
 */
proto.transaction.GetTransactionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.GetTransactionsRequest;
  return proto.transaction.GetTransactionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.GetTransactionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.GetTransactionsRequest}
 */
proto.transaction.GetTransactionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setApikey(value);
      break;
    case 2:
      var value = new proto.transaction.TransactionQueryCriteria;
      reader.readMessage(value,proto.transaction.TransactionQueryCriteria.deserializeBinaryFromReader);
      msg.setQuerycriteria(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.GetTransactionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.GetTransactionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.GetTransactionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.GetTransactionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApikey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getQuerycriteria();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.transaction.TransactionQueryCriteria.serializeBinaryToWriter
    );
  }
};


/**
 * optional string apiKey = 1;
 * @return {string}
 */
proto.transaction.GetTransactionsRequest.prototype.getApikey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.GetTransactionsRequest} returns this
 */
proto.transaction.GetTransactionsRequest.prototype.setApikey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TransactionQueryCriteria queryCriteria = 2;
 * @return {?proto.transaction.TransactionQueryCriteria}
 */
proto.transaction.GetTransactionsRequest.prototype.getQuerycriteria = function() {
  return /** @type{?proto.transaction.TransactionQueryCriteria} */ (
    jspb.Message.getWrapperField(this, proto.transaction.TransactionQueryCriteria, 2));
};


/**
 * @param {?proto.transaction.TransactionQueryCriteria|undefined} value
 * @return {!proto.transaction.GetTransactionsRequest} returns this
*/
proto.transaction.GetTransactionsRequest.prototype.setQuerycriteria = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.transaction.GetTransactionsRequest} returns this
 */
proto.transaction.GetTransactionsRequest.prototype.clearQuerycriteria = function() {
  return this.setQuerycriteria(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.transaction.GetTransactionsRequest.prototype.hasQuerycriteria = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.transaction.GetTransactionsResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.GetTransactionsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.GetTransactionsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.GetTransactionsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.GetTransactionsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    response: (f = msg.getResponse()) && proto.transaction.TransactionRPCResponse.toObject(includeInstance, f),
    transactionsList: jspb.Message.toObjectList(msg.getTransactionsList(),
    proto.transaction.Transaction.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.GetTransactionsResponse}
 */
proto.transaction.GetTransactionsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.GetTransactionsResponse;
  return proto.transaction.GetTransactionsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.GetTransactionsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.GetTransactionsResponse}
 */
proto.transaction.GetTransactionsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.transaction.TransactionRPCResponse;
      reader.readMessage(value,proto.transaction.TransactionRPCResponse.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    case 3:
      var value = new proto.transaction.Transaction;
      reader.readMessage(value,proto.transaction.Transaction.deserializeBinaryFromReader);
      msg.addTransactions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.GetTransactionsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.GetTransactionsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.GetTransactionsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.GetTransactionsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.transaction.TransactionRPCResponse.serializeBinaryToWriter
    );
  }
  f = message.getTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.transaction.Transaction.serializeBinaryToWriter
    );
  }
};


/**
 * optional TransactionRPCResponse response = 1;
 * @return {?proto.transaction.TransactionRPCResponse}
 */
proto.transaction.GetTransactionsResponse.prototype.getResponse = function() {
  return /** @type{?proto.transaction.TransactionRPCResponse} */ (
    jspb.Message.getWrapperField(this, proto.transaction.TransactionRPCResponse, 1));
};


/**
 * @param {?proto.transaction.TransactionRPCResponse|undefined} value
 * @return {!proto.transaction.GetTransactionsResponse} returns this
*/
proto.transaction.GetTransactionsResponse.prototype.setResponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.transaction.GetTransactionsResponse} returns this
 */
proto.transaction.GetTransactionsResponse.prototype.clearResponse = function() {
  return this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.transaction.GetTransactionsResponse.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Transaction transactions = 3;
 * @return {!Array<!proto.transaction.Transaction>}
 */
proto.transaction.GetTransactionsResponse.prototype.getTransactionsList = function() {
  return /** @type{!Array<!proto.transaction.Transaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.transaction.Transaction, 3));
};


/**
 * @param {!Array<!proto.transaction.Transaction>} value
 * @return {!proto.transaction.GetTransactionsResponse} returns this
*/
proto.transaction.GetTransactionsResponse.prototype.setTransactionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.transaction.Transaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.transaction.Transaction}
 */
proto.transaction.GetTransactionsResponse.prototype.addTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.transaction.Transaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.transaction.GetTransactionsResponse} returns this
 */
proto.transaction.GetTransactionsResponse.prototype.clearTransactionsList = function() {
  return this.setTransactionsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.transaction.WithdrawMoneyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.transaction.WithdrawMoneyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.WithdrawMoneyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.WithdrawMoneyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ownerid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    ownertable: jspb.Message.getFieldWithDefault(msg, 2, ""),
    walletid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    externalwalletid: jspb.Message.getFieldWithDefault(msg, 4, 0),
    externalbankcode: jspb.Message.getFieldWithDefault(msg, 5, 0),
    externalacountnumber: jspb.Message.getFieldWithDefault(msg, 6, 0),
    amount: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.WithdrawMoneyRequest}
 */
proto.transaction.WithdrawMoneyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.transaction.WithdrawMoneyRequest;
  return proto.transaction.WithdrawMoneyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.WithdrawMoneyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.WithdrawMoneyRequest}
 */
proto.transaction.WithdrawMoneyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setOwnerid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnertable(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setWalletid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setExternalwalletid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setExternalbankcode(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setExternalacountnumber(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setAmount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.WithdrawMoneyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.transaction.WithdrawMoneyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.WithdrawMoneyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.WithdrawMoneyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOwnerid();
  if (f !== 0) {
    writer.writeSint64(
      1,
      f
    );
  }
  f = message.getOwnertable();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getWalletid();
  if (f !== 0) {
    writer.writeSint64(
      3,
      f
    );
  }
  f = message.getExternalwalletid();
  if (f !== 0) {
    writer.writeSint64(
      4,
      f
    );
  }
  f = message.getExternalbankcode();
  if (f !== 0) {
    writer.writeSint64(
      5,
      f
    );
  }
  f = message.getExternalacountnumber();
  if (f !== 0) {
    writer.writeSint64(
      6,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0) {
    writer.writeSint64(
      7,
      f
    );
  }
};


/**
 * optional sint64 OwnerID = 1;
 * @return {number}
 */
proto.transaction.WithdrawMoneyRequest.prototype.getOwnerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.WithdrawMoneyRequest} returns this
 */
proto.transaction.WithdrawMoneyRequest.prototype.setOwnerid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string OwnerTable = 2;
 * @return {string}
 */
proto.transaction.WithdrawMoneyRequest.prototype.getOwnertable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.transaction.WithdrawMoneyRequest} returns this
 */
proto.transaction.WithdrawMoneyRequest.prototype.setOwnertable = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional sint64 WalletID = 3;
 * @return {number}
 */
proto.transaction.WithdrawMoneyRequest.prototype.getWalletid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.WithdrawMoneyRequest} returns this
 */
proto.transaction.WithdrawMoneyRequest.prototype.setWalletid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional sint64 ExternalWalletID = 4;
 * @return {number}
 */
proto.transaction.WithdrawMoneyRequest.prototype.getExternalwalletid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.WithdrawMoneyRequest} returns this
 */
proto.transaction.WithdrawMoneyRequest.prototype.setExternalwalletid = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional sint64 ExternalBankCode = 5;
 * @return {number}
 */
proto.transaction.WithdrawMoneyRequest.prototype.getExternalbankcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.WithdrawMoneyRequest} returns this
 */
proto.transaction.WithdrawMoneyRequest.prototype.setExternalbankcode = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional sint64 ExternalAcountNumber = 6;
 * @return {number}
 */
proto.transaction.WithdrawMoneyRequest.prototype.getExternalacountnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.WithdrawMoneyRequest} returns this
 */
proto.transaction.WithdrawMoneyRequest.prototype.setExternalacountnumber = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional sint64 Amount = 7;
 * @return {number}
 */
proto.transaction.WithdrawMoneyRequest.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.transaction.WithdrawMoneyRequest} returns this
 */
proto.transaction.WithdrawMoneyRequest.prototype.setAmount = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


goog.object.extend(exports, proto.transaction);
