/**
 * @fileoverview gRPC-Web generated client stub for transaction
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: transaction.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var wallet_pb = require('./wallet_pb.js')
const proto = {};
proto.transaction = require('./transaction_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.transaction.TransactionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.transaction.TransactionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.transaction.TransferMoneyRequest,
 *   !proto.transaction.TransactionRPCResponse>}
 */
const methodDescriptor_TransactionService_TransferMoney = new grpc.web.MethodDescriptor(
  '/transaction.TransactionService/TransferMoney',
  grpc.web.MethodType.UNARY,
  proto.transaction.TransferMoneyRequest,
  proto.transaction.TransactionRPCResponse,
  /**
   * @param {!proto.transaction.TransferMoneyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.transaction.TransactionRPCResponse.deserializeBinary
);


/**
 * @param {!proto.transaction.TransferMoneyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.transaction.TransactionRPCResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.transaction.TransactionRPCResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.transaction.TransactionServiceClient.prototype.transferMoney =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/transaction.TransactionService/TransferMoney',
      request,
      metadata || {},
      methodDescriptor_TransactionService_TransferMoney,
      callback);
};


/**
 * @param {!proto.transaction.TransferMoneyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.transaction.TransactionRPCResponse>}
 *     Promise that resolves to the response
 */
proto.transaction.TransactionServicePromiseClient.prototype.transferMoney =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/transaction.TransactionService/TransferMoney',
      request,
      metadata || {},
      methodDescriptor_TransactionService_TransferMoney);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.transaction.TopUpWalletRequest,
 *   !proto.transaction.TransactionRPCResponse>}
 */
const methodDescriptor_TransactionService_TopUpWallet = new grpc.web.MethodDescriptor(
  '/transaction.TransactionService/TopUpWallet',
  grpc.web.MethodType.UNARY,
  proto.transaction.TopUpWalletRequest,
  proto.transaction.TransactionRPCResponse,
  /**
   * @param {!proto.transaction.TopUpWalletRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.transaction.TransactionRPCResponse.deserializeBinary
);


/**
 * @param {!proto.transaction.TopUpWalletRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.transaction.TransactionRPCResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.transaction.TransactionRPCResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.transaction.TransactionServiceClient.prototype.topUpWallet =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/transaction.TransactionService/TopUpWallet',
      request,
      metadata || {},
      methodDescriptor_TransactionService_TopUpWallet,
      callback);
};


/**
 * @param {!proto.transaction.TopUpWalletRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.transaction.TransactionRPCResponse>}
 *     Promise that resolves to the response
 */
proto.transaction.TransactionServicePromiseClient.prototype.topUpWallet =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/transaction.TransactionService/TopUpWallet',
      request,
      metadata || {},
      methodDescriptor_TransactionService_TopUpWallet);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.transaction.GetTransactionsRequest,
 *   !proto.transaction.GetTransactionsResponse>}
 */
const methodDescriptor_TransactionService_GetTransactions = new grpc.web.MethodDescriptor(
  '/transaction.TransactionService/GetTransactions',
  grpc.web.MethodType.UNARY,
  proto.transaction.GetTransactionsRequest,
  proto.transaction.GetTransactionsResponse,
  /**
   * @param {!proto.transaction.GetTransactionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.transaction.GetTransactionsResponse.deserializeBinary
);


/**
 * @param {!proto.transaction.GetTransactionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.transaction.GetTransactionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.transaction.GetTransactionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.transaction.TransactionServiceClient.prototype.getTransactions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/transaction.TransactionService/GetTransactions',
      request,
      metadata || {},
      methodDescriptor_TransactionService_GetTransactions,
      callback);
};


/**
 * @param {!proto.transaction.GetTransactionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.transaction.GetTransactionsResponse>}
 *     Promise that resolves to the response
 */
proto.transaction.TransactionServicePromiseClient.prototype.getTransactions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/transaction.TransactionService/GetTransactions',
      request,
      metadata || {},
      methodDescriptor_TransactionService_GetTransactions);
};


module.exports = proto.transaction;

