// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: shifter.proto

package shifter_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShifterServiceClient is the client API for ShifterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShifterServiceClient interface {
	GetFrontlinerBulk(ctx context.Context, in *GetFrontlinerBulkRequest, opts ...grpc.CallOption) (*GetFrontlinerBulkResponse, error)
}

type shifterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShifterServiceClient(cc grpc.ClientConnInterface) ShifterServiceClient {
	return &shifterServiceClient{cc}
}

func (c *shifterServiceClient) GetFrontlinerBulk(ctx context.Context, in *GetFrontlinerBulkRequest, opts ...grpc.CallOption) (*GetFrontlinerBulkResponse, error) {
	out := new(GetFrontlinerBulkResponse)
	err := c.cc.Invoke(ctx, "/wallet.ShifterService/GetFrontlinerBulk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShifterServiceServer is the server API for ShifterService service.
// All implementations must embed UnimplementedShifterServiceServer
// for forward compatibility
type ShifterServiceServer interface {
	GetFrontlinerBulk(context.Context, *GetFrontlinerBulkRequest) (*GetFrontlinerBulkResponse, error)
	mustEmbedUnimplementedShifterServiceServer()
}

// UnimplementedShifterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShifterServiceServer struct {
}

func (UnimplementedShifterServiceServer) GetFrontlinerBulk(context.Context, *GetFrontlinerBulkRequest) (*GetFrontlinerBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrontlinerBulk not implemented")
}
func (UnimplementedShifterServiceServer) mustEmbedUnimplementedShifterServiceServer() {}

// UnsafeShifterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShifterServiceServer will
// result in compilation errors.
type UnsafeShifterServiceServer interface {
	mustEmbedUnimplementedShifterServiceServer()
}

func RegisterShifterServiceServer(s grpc.ServiceRegistrar, srv ShifterServiceServer) {
	s.RegisterService(&ShifterService_ServiceDesc, srv)
}

func _ShifterService_GetFrontlinerBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrontlinerBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShifterServiceServer).GetFrontlinerBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.ShifterService/GetFrontlinerBulk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShifterServiceServer).GetFrontlinerBulk(ctx, req.(*GetFrontlinerBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShifterService_ServiceDesc is the grpc.ServiceDesc for ShifterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShifterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.ShifterService",
	HandlerType: (*ShifterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFrontlinerBulk",
			Handler:    _ShifterService_GetFrontlinerBulk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shifter.proto",
}
