// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: shifter.proto

package shifter_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response int32  `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RPCResponse) Reset() {
	*x = RPCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shifter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponse) ProtoMessage() {}

func (x *RPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shifter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponse.ProtoReflect.Descriptor instead.
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return file_shifter_proto_rawDescGZIP(), []int{0}
}

func (x *RPCResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

func (x *RPCResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFrontlinerBulkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey       string   `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	FrontlinerId []uint64 `protobuf:"varint,2,rep,packed,name=FrontlinerId,proto3" json:"FrontlinerId,omitempty"`
}

func (x *GetFrontlinerBulkRequest) Reset() {
	*x = GetFrontlinerBulkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shifter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFrontlinerBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontlinerBulkRequest) ProtoMessage() {}

func (x *GetFrontlinerBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shifter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontlinerBulkRequest.ProtoReflect.Descriptor instead.
func (*GetFrontlinerBulkRequest) Descriptor() ([]byte, []int) {
	return file_shifter_proto_rawDescGZIP(), []int{1}
}

func (x *GetFrontlinerBulkRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetFrontlinerBulkRequest) GetFrontlinerId() []uint64 {
	if x != nil {
		return x.FrontlinerId
	}
	return nil
}

type GetFrontlinerBulkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response   *RPCResponse  `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Frontliner []*Frontliner `protobuf:"bytes,2,rep,name=Frontliner,proto3" json:"Frontliner,omitempty"`
}

func (x *GetFrontlinerBulkResponse) Reset() {
	*x = GetFrontlinerBulkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shifter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFrontlinerBulkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontlinerBulkResponse) ProtoMessage() {}

func (x *GetFrontlinerBulkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shifter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontlinerBulkResponse.ProtoReflect.Descriptor instead.
func (*GetFrontlinerBulkResponse) Descriptor() ([]byte, []int) {
	return file_shifter_proto_rawDescGZIP(), []int{2}
}

func (x *GetFrontlinerBulkResponse) GetResponse() *RPCResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetFrontlinerBulkResponse) GetFrontliner() []*Frontliner {
	if x != nil {
		return x.Frontliner
	}
	return nil
}

// Frontliner Model Definition
type Frontliner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Gender         string `protobuf:"bytes,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	FrontlinerType string `protobuf:"bytes,4,opt,name=FrontlinerType,proto3" json:"FrontlinerType,omitempty"`
	IsApproved     bool   `protobuf:"varint,5,opt,name=IsApproved,proto3" json:"IsApproved,omitempty"`
	CreatedAt      string `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *Frontliner) Reset() {
	*x = Frontliner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shifter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frontliner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frontliner) ProtoMessage() {}

func (x *Frontliner) ProtoReflect() protoreflect.Message {
	mi := &file_shifter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frontliner.ProtoReflect.Descriptor instead.
func (*Frontliner) Descriptor() ([]byte, []int) {
	return file_shifter_proto_rawDescGZIP(), []int{3}
}

func (x *Frontliner) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Frontliner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Frontliner) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Frontliner) GetFrontlinerType() string {
	if x != nil {
		return x.FrontlinerType
	}
	return ""
}

func (x *Frontliner) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *Frontliner) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_shifter_proto protoreflect.FileDescriptor

var file_shifter_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x68, 0x69, 0x66, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x43, 0x0a, 0x0b, 0x52, 0x50, 0x43, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x56, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x42, 0x75, 0x6c,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79,
	0x12, 0x22, 0x0a, 0x0c, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0c, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x6c, 0x69, 0x6e,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e,
	0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x52, 0x50,
	0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x6c, 0x69, 0x6e, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x2e, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x0a, 0x46, 0x72, 0x6f,
	0x6e, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x22, 0xae, 0x01, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6e,
	0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x46, 0x72, 0x6f, 0x6e,
	0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x49, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0x6a, 0x0a, 0x0e, 0x53, 0x68, 0x69, 0x66,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x42, 0x75, 0x6c, 0x6b, 0x12,
	0x20, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6e,
	0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72,
	0x6f, 0x6e, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x72, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x73, 0x68, 0x69, 0x66, 0x74, 0x65,
	0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_shifter_proto_rawDescOnce sync.Once
	file_shifter_proto_rawDescData = file_shifter_proto_rawDesc
)

func file_shifter_proto_rawDescGZIP() []byte {
	file_shifter_proto_rawDescOnce.Do(func() {
		file_shifter_proto_rawDescData = protoimpl.X.CompressGZIP(file_shifter_proto_rawDescData)
	})
	return file_shifter_proto_rawDescData
}

var file_shifter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shifter_proto_goTypes = []interface{}{
	(*RPCResponse)(nil),               // 0: wallet.RPCResponse
	(*GetFrontlinerBulkRequest)(nil),  // 1: wallet.GetFrontlinerBulkRequest
	(*GetFrontlinerBulkResponse)(nil), // 2: wallet.GetFrontlinerBulkResponse
	(*Frontliner)(nil),                // 3: wallet.Frontliner
}
var file_shifter_proto_depIdxs = []int32{
	0, // 0: wallet.GetFrontlinerBulkResponse.response:type_name -> wallet.RPCResponse
	3, // 1: wallet.GetFrontlinerBulkResponse.Frontliner:type_name -> wallet.Frontliner
	1, // 2: wallet.ShifterService.GetFrontlinerBulk:input_type -> wallet.GetFrontlinerBulkRequest
	2, // 3: wallet.ShifterService.GetFrontlinerBulk:output_type -> wallet.GetFrontlinerBulkResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shifter_proto_init() }
func file_shifter_proto_init() {
	if File_shifter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shifter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shifter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFrontlinerBulkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shifter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFrontlinerBulkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shifter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frontliner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shifter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shifter_proto_goTypes,
		DependencyIndexes: file_shifter_proto_depIdxs,
		MessageInfos:      file_shifter_proto_msgTypes,
	}.Build()
	File_shifter_proto = out.File
	file_shifter_proto_rawDesc = nil
	file_shifter_proto_goTypes = nil
	file_shifter_proto_depIdxs = nil
}
